# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppColSum_sqrt <- function(A) {
    .Call('_adcf_cppColSum_sqrt', PACKAGE = 'adcf', A)
}

dist_to_dcov <- function(x, y) {
    .Call('_adcf_dist_to_dcov', PACKAGE = 'adcf', x, y)
}

